services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chatwoot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chatwoot_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - '1025:1025'
      - '8025:8025'

  chatwoot:
    image: chatwoot/chatwoot:v3.12.0
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker
      
      # 数据库配置
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: chatwoot_password
      POSTGRES_DATABASE: chatwoot
      
      # Redis配置
      REDIS_URL: redis://redis:6379
      
      # 应用配置
      SECRET_KEY_BASE: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2
      FRONTEND_URL: http://localhost:3000
      
      # 功能配置
      ENABLE_ACCOUNT_SIGNUP: true
      MAILER_SENDER_EMAIL: Chatwoot <noreply@localhost>

      # 启用所有功能
      ENABLE_FEATURE_MACROS: true
      ENABLE_FEATURE_LABELS: true
      ENABLE_FEATURE_INBOX_GREETING: true
      ENABLE_FEATURE_TEAM_MANAGEMENT: true
      ENABLE_FEATURE_AUTO_RESOLVE_CONVERSATIONS: true
      ENABLE_FEATURE_CAMPAIGNS: true
      ENABLE_FEATURE_INTEGRATIONS: true
      ENABLE_FEATURE_REPORTS: true
      ENABLE_FEATURE_AGENT_BOTS: true
      ENABLE_FEATURE_HELP_CENTER: true
      ENABLE_FEATURE_VOICE_RECORDER: true
      ENABLE_FEATURE_EMOJI_PICKER: true
      ENABLE_FEATURE_ATTACHMENT_PROCESSOR: true
      ENABLE_FEATURE_ENHANCED_AGENTS: true
      ENABLE_FEATURE_CUSTOM_ATTRIBUTES: true
      ENABLE_FEATURE_WEBHOOKS: true
      ENABLE_FEATURE_SLACK_INTEGRATION: true
      ENABLE_FEATURE_FACEBOOK_INTEGRATION: true
      ENABLE_FEATURE_TWITTER_INTEGRATION: true
      ENABLE_FEATURE_WHATSAPP_INTEGRATION: true
      ENABLE_FEATURE_SMS_INTEGRATION: true
      ENABLE_FEATURE_EMAIL_INTEGRATION: true
      ENABLE_FEATURE_WEBSITE_INTEGRATION: true
      ENABLE_FEATURE_API_INTEGRATION: true

      # 邮件配置
      SMTP_DOMAIN: localhost
      SMTP_ADDRESS: mailhog
      SMTP_PORT: 1025
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      SMTP_AUTHENTICATION: ""
      SMTP_ENABLE_STARTTLS_AUTO: false
      SMTP_OPENSSL_VERIFY_MODE: none

      # 存储配置
      ACTIVE_STORAGE_SERVICE: local

      # 日志配置
      RAILS_LOG_TO_STDOUT: true
      LOG_LEVEL: info
      
    entrypoint: |
      sh -c '
        echo "等待数据库启动..."
        while ! pg_isready -h postgres -U postgres; do
          sleep 1
        done
        
        echo "创建数据库..."
        bundle exec rails db:create || true
        
        echo "加载基础schema..."
        DISABLE_DATABASE_ENVIRONMENT_CHECK=1 bundle exec rails db:schema:load || true
        
        echo "启动Rails服务器..."
        bundle exec rails server -b 0.0.0.0 -p 3000
      '
    volumes:
      - storage_data:/app/storage

  sidekiq:
    image: chatwoot/chatwoot:v3.12.0
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker

      # 数据库配置
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: chatwoot_password
      POSTGRES_DATABASE: chatwoot

      # Redis配置
      REDIS_URL: redis://redis:6379

      # 应用配置
      SECRET_KEY_BASE: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2

      # 日志配置
      RAILS_LOG_TO_STDOUT: true
      LOG_LEVEL: info

    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    volumes:
      - storage_data:/app/storage

volumes:
  postgres_data:
  redis_data:
  storage_data:
